version: '3'
services:
  entrypoint:
    image: gergob/cyber-auth-be-proxy
    container_name: cyber-auth-be-proxy
    build: ./proxy
    ports:
     - "8080:8080"
     - "9229:9229"
    networks:
      - node_net
    links:
      - auth
      - registration
      - userservice
    depends_on:
      - auth
      - registration
      - userservice
    volumes:
      - ./ssl/cyberauth_proxy.crt:/var/opt/certs/cyberauth_proxy.crt:ro
      - ./ssl/cyberauth_proxy.key:/var/opt/certs/cyberauth_proxy.key:ro
      - ./ssl/cyberauth_ca.crt:/var/opt/certs/cyberauth_ca.crt:ro
      - /private/etc/localtime:/etc/localtime:ro
    environment:
      - CONNECTION_STRING=mongodb://credentialstore:27017/
  auth:
    networks:
      - node_net
    links:
      - credentialstore
    depends_on:
      - credentialstore
    image: gergob/cyber-auth-be-auth
    container_name: cyber-auth-be-auth
    build: ./auth
    ports:
     - "8081:8000"
    volumes:
      - ./ssl/cyberauth_auth.crt:/var/opt/certs/cyberauth_auth.crt:ro
      - ./ssl/cyberauth_auth.key:/var/opt/certs/cyberauth_auth.key:ro
      - ./ssl/cyberauth_auth.key:/var/opt/jwt/jwt_signer.key:ro
      - ./ssl/cyberauth_auth.key:/var/opt/jwt/jwt_signer.pubkey:ro
      - ./ssl/cyberauth_ca.crt:/var/opt/certs/cyberauth_ca.crt:ro
      - /private/etc/localtime:/etc/localtime:ro
    environment:
      - CONNECTION_STRING=mongodb://credentialstore:27017/
  registration:
    networks:
      - node_net
    links:
      - credentialstore
    depends_on:
      - credentialstore
    image: gergob/cyber-auth-be-registration
    container_name: cyber-auth-be-registration
    build: ./registration
    ports:
      - "8082:8000"
    volumes:
      - ./ssl/cyberauth_registration.crt:/var/opt/certs/cyberauth_registration.crt:ro
      - ./ssl/cyberauth_registration.key:/var/opt/certs/cyberauth_registration.key:ro
      - ./ssl/cyberauth_ca.crt:/var/opt/certs/cyberauth_ca.crt:ro
      - ./ssl/cyberauth_auth.key:/var/opt/jwt/jwt_signer.pubkey:ro
      - /private/etc/localtime:/etc/localtime:ro
    environment:
      - CONNECTION_STRING=mongodb://credentialstore:27017/
  userservice:
    networks:
      - node_net
    links:
      - credentialstore
    depends_on:
      - credentialstore
    image: gergob/cyber-auth-be-userservice
    container_name: cyber-auth-be-userservice
    build: ./user
    ports:
      - "8083:8000"
    volumes:
      - ./ssl/cyberauth_registration.crt:/var/opt/certs/cyberauth_user.crt:ro
      - ./ssl/cyberauth_registration.key:/var/opt/certs/cyberauth_user.key:ro
      - ./ssl/cyberauth_ca.crt:/var/opt/certs/cyberauth_ca.crt:ro
      - ./ssl/cyberauth_auth.key:/var/opt/jwt/jwt_signer.pubkey:ro
      - /private/etc/localtime:/etc/localtime:ro
    environment:
      - CONNECTION_STRING=mongodb://credentialstore:27017/
  credentialstore:
      networks:
        - node_net
      image: mongo
      container_name: cyber-auth-be-credentialstore
      ports:
        - "27017:27017"
      volumes:
        - ./data/db:/data/db
        - /private/etc/localtime:/etc/localtime:ro
networks:
  node_net:
    driver: bridge
