# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  proxy-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install npm dependencies for proxy component
      run: cd proxy && npm install
  proxy-test:
    runs-on: ubuntu-latest
    needs: proxy-install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Execute tests for proxy component
        run: cd proxy && npm test
  proxy-audit:
    runs-on: ubuntu-latest
    needs: proxy-install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Execute npm audit on proxy component
        run: cd proxy && npm audit
  proxy-lint:
    runs-on: ubuntu-latest
    needs: proxy-install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Execute npm audit on proxy component
        run: cd proxy && npm run lint
  auth-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install npm dependencies for proxy component
        run: cd auth && npm install
  auth-test:
    runs-on: ubuntu-latest
    needs: auth-install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Execute tests for proxy component
        run: cd auth && npm test
  auth-audit:
    runs-on: ubuntu-latest
    needs: auth-install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Execute npm audit on proxy component
        run: cd auth && npm audit
  auth-lint:
    runs-on: ubuntu-latest
    needs: auth-install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Execute npm audit on proxy component
        run: cd auth && npm run lint
  registration-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install npm dependencies for proxy component
        run: cd registration && npm install
  registration-test:
    runs-on: ubuntu-latest
    needs: registration-install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Execute tests for proxy component
        run: cd registration && npm test
  registration-coverage:
    runs-on: ubuntu-latest
    needs: registration-test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Execute tests for proxy component
        run: cd registration && npm run coverage
  registration-audit:
    runs-on: ubuntu-latest
    needs: registration-install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Execute npm audit on proxy component
        run: cd registration && npm audit
  registration-lint:
    runs-on: ubuntu-latest
    needs: registration-install
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Execute npm audit on proxy component
        run: cd registration && npm run lint
