# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  proxy-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install npm dependencies for proxy component
        run: cd proxy && npm install
      - name: Execute tests for proxy component
        run: cd proxy && npm test
      - name: Execute coverage report for registration component
        run: cd proxy && npm run coverage
      - name: Execute npm audit on proxy component
        run: cd proxy && npm audit
      - name: Execute eslint on proxy component
        run: cd proxy && npm run lint
  auth-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install npm dependencies for auth component
        run: cd auth && npm install
      - name: Execute tests for auth component
        run: cd auth && npm test
      - name: Execute npm audit on auth component
        run: cd auth && npm audit
      - name: Execute eslint on auth component
        run: cd auth && npm run lint
  registration-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install npm dependencies for registration component
        run: cd registration && npm install
      - name: Execute tests for registration component
        run: cd registration && npm test
      - name: Execute coverage report for registration component
        run: cd registration && npm run coverage
      - name: Execute npm audit on registration component
        run: cd registration && npm audit
      - name: Execute eslint on registration component
        run: cd registration && npm run lint
